// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohnmcdqiwvrxlmbznrcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obm1jZHFpd3ZyeGxtYnpucmNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMjA1MDIsImV4cCI6MjA2NzU5NjUwMn0.Vjc8jQysz_ZbfRRk9byQfAGyKxrtng0sRgd23-DrAjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});